### ISSUE TITLE
Linux toolchain is missing liblto_plugin.so

### ISSUE THREAD

**Issue by rsn8887** [vitasdk/autobuilds#9]
Since switching to a static Linux toolchain (see https://github.com/vitasdk/autobuilds/pull/6), the file liblto_plugin.so is missing. Instead there's only a useless liblto_plugin.a file. 

liblto_plugin.so is needed by arm-vita-eabi-gcc-ar binary to do link-time-optimization (lto). Switching to arm-vita-eabi-ar works but then there's no lto at all

**Comment by rsn8887** [comment]
This caused it: https://github.com/vitasdk/autobuilds/commit/8d6e45ab6fd23e1ece3bdfdf38ce2a919ae41b21

**Comment by endrift** [comment]
Just hit this myself. It prevents building mGBA using the static toolchain.

**Comment by xyzz** [comment]
I suggest reverting #6 it was a mistake @frangarcj
